#include "/Engine/Public/Platform.ush"

float4x4 WorldViewProjection;
float3 EyePosToVolume;

struct FVolumePixelInput
{
	float4 OutPosition : SV_Position;
	float3 VolumePosition : POSITION;
};

void VolumeBackVS(in float3 VertexPosition : ATTRIBUTE,
					out FVolumePixelInput Result)
{
	
}

void VolumeBackPS(in FVolumePixelInput PSInput,
					out float4 OutColor : SV_Target0)
{
	
}

void VolumeFrontPS()
{
	
}